name: 'actions-vault-aws-secret'
description: 'Fetch and export AWS temporary credentials for github_actions'

inputs:
  environment:  # id of input
    description: 'the aws environment, e.g: dev or prod'
    required: true
  vault_address:  # id of input
    description: 'the address of vault'
    required: false
    default: 'https://vault.prod.hatch.live'
  vault_aws_secret_backend_role:
    description: 'the aws secret backend role name in vault'
    required: false
    default: 'vault_aws_secret'

outputs:
  aws_access_key_id:
    description: 'aws access key id'
    value: ${{ steps.fetch-aws-secret.outputs.aws_access_key_id }}
  aws_secret_access_key:
    description: 'aws secret access key'
    value: ${{ steps.fetch-aws-secret.outputs.aws_secret_access_key }}
  aws_session_token:
    description: 'aws session token'
    value: ${{ steps.fetch-aws-secret.outputs.aws_session_token }}
  assume_role_arn:
    description: 'assumed role arn'
    value: ${{ steps.fetch-aws-secret.outputs.assume_role_arn }}
  vault_aws_secret_backend_role:
    description: 'assumed role arn'
    value: ${{ steps.fetch-aws-secret.outputs.vault_aws_secret_backend_role }}

runs:
  using: "composite"
  steps:
    # Login with approle then export temporary aws sts credential to env vars
    - name: fetch-aws-secret
      id: fetch-aws-secret
      run: ${{ github.action_path }}/aws_sts_secret.sh
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        VAULT_ADDR: ${{ inputs.vault_address }}
        VAULT_AWS_SECRET_BACKEND_ROLE: ${{ inputs.vault_aws_secret_backend_role }}
        ROLE_ID: ${{ secrets.VAULT_APPROLE_GITHUB_ACTIONS_ROLE_ID }}
        SECRET_ID: ${{ secrets.VAULT_APPROLE_GITHUB_ACTIONS_SECRET_ID }}

